# -*- coding: utf-8 -*-
"""Tic_TacToe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g1lIEVJB5WdV3DMOFukbIVOrvYbE3OHD

## **Tic Tac Toe Game**
"""

def print_board():

  print("  -  "+ "|"+"  -  "+"|"+"  -  \n ----------------\n  -  "+ "|"+"  -  "+"|"+"  -  \n ----------------\n  -  "+ "|"+"  -  "+"|"+"  -  \n")
  
print_board()

positons = ["1","2","3","4","5","6","7","8","9"]

a=10